wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1681992726.797621
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 23
      - 37
      4: 3.10.6
      5: 0.14.0
      8:
      - 5
gamma:
  desc: null
  value: 0.9802249083991836
